version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#      - ZOO_ENABLE_AUTH=yes
#      - ZOO_SERVER_USERS=user
#      - ZOO_SERVER_PASSWORDS=secret
#      - ZOO_CLIENT_USER=user
#      - ZOO_CLIENT_PASSWORD=secret